const cloneDeep = (value) => JSON.parse(JSON.stringify(value))

export const DEMO_USER = {
  id: 'user-001',
  name: 'Rita Nwosu',
  email: 'rita@nexus.app',
  avatar: 'https://i.pravatar.cc/120?img=47',
  role: 'owner',
  title: 'Head of Growth',
}

export const DEMO_CREDENTIALS = {
  email: 'rita@nexus.app',
  password: 'N3xus@2026',
}

export const TWO_FA_CONFIG = {
  method: 'app',
  validCode: '246810',
  backupCodes: ['ALFA-90KP', 'BRAV-28QX', 'NOVA-76TP'],
}

export const WORKSPACES = [
  {
    id: 'ws-aurora',
    company: 'Aurora Labs',
    initials: 'AL',
    color: '#E8621A',
    role: 'admin',
    timezone: 'Africa/Lagos',
    platforms: ['instagram', 'x', 'linkedin', 'youtube'],
    membersCount: 14,
  },
  {
    id: 'ws-vanta',
    company: 'Vanta Motion',
    initials: 'VM',
    color: '#3B9EE8',
    role: 'member',
    timezone: 'Europe/London',
    platforms: ['instagram', 'tiktok', 'x'],
    membersCount: 9,
  },
  {
    id: 'ws-rivet',
    company: 'Rivet Retail',
    initials: 'RR',
    color: '#2ECC8A',
    role: 'admin',
    timezone: 'America/New_York',
    platforms: ['facebook', 'instagram', 'whatsapp'],
    membersCount: 21,
  },
]

export const MOCK_WORKSPACES = WORKSPACES

export const POSTS_BY_WORKSPACE = {
  'ws-aurora': [
    {
      id: 'post-aur-001',
      workspaceId: 'ws-aurora',
      title: 'Spring Launch Reel',
      caption: 'From idea to impact. Meet the workflow behind our latest launch.',
      platforms: ['instagram', 'x'],
      status: 'published',
      createdAt: '2026-04-21T08:00:00Z',
      publishedAt: '2026-04-21T10:10:00Z',
      scheduledFor: null,
      media: [{ type: 'video', url: '/assets/posts/spring-launch.mp4' }],
      tags: ['campaign', 'launch', 'reel'],
      authorId: 'user-001',
      metrics: {
        impressions: 128400,
        reach: 93400,
        likes: 7210,
        comments: 412,
        shares: 298,
        saves: 680,
        clicks: 1214,
        engagementRate: 8.37,
      },
    },
    {
      id: 'post-aur-002',
      workspaceId: 'ws-aurora',
      title: 'BTS Carousel',
      caption: 'A behind-the-scenes look at our product sprint board.',
      platforms: ['linkedin', 'instagram'],
      status: 'scheduled',
      createdAt: '2026-04-22T12:16:00Z',
      publishedAt: null,
      scheduledFor: '2026-04-26T11:30:00Z',
      media: [{ type: 'image', url: '/assets/posts/bts-1.png' }],
      tags: ['behind-the-scenes', 'team', 'carousel'],
      authorId: 'user-001',
      metrics: {
        impressions: 0,
        reach: 0,
        likes: 0,
        comments: 0,
        shares: 0,
        saves: 0,
        clicks: 0,
        engagementRate: 0,
      },
    },
    {
      id: 'post-aur-003',
      workspaceId: 'ws-aurora',
      title: 'Community Spotlight',
      caption: 'Celebrating creators building with NEXUS every week.',
      platforms: ['x'],
      status: 'draft',
      createdAt: '2026-04-23T09:02:00Z',
      publishedAt: null,
      scheduledFor: null,
      media: [],
      tags: ['community'],
      authorId: 'user-001',
      metrics: {
        impressions: 0,
        reach: 0,
        likes: 0,
        comments: 0,
        shares: 0,
        saves: 0,
        clicks: 0,
        engagementRate: 0,
      },
    },
    {
      id: 'post-aur-004',
      workspaceId: 'ws-aurora',
      title: 'Analytics Snapshot',
      caption: 'Q2 benchmark highlights for growth teams.',
      platforms: ['linkedin'],
      status: 'published',
      createdAt: '2026-04-18T06:22:00Z',
      publishedAt: '2026-04-19T08:00:00Z',
      scheduledFor: null,
      media: [{ type: 'image', url: '/assets/posts/analytics-snapshot.png' }],
      tags: ['analytics', 'benchmark'],
      authorId: 'user-001',
      metrics: {
        impressions: 74300,
        reach: 55200,
        likes: 2780,
        comments: 220,
        shares: 164,
        saves: 340,
        clicks: 890,
        engagementRate: 6.31,
      },
    },
  ],
  'ws-vanta': [
    {
      id: 'post-van-001',
      workspaceId: 'ws-vanta',
      title: 'Motion Clip #13',
      caption: 'Fast cuts. Strong story. Better conversion.',
      platforms: ['tiktok', 'instagram'],
      status: 'published',
      createdAt: '2026-04-20T07:00:00Z',
      publishedAt: '2026-04-20T11:45:00Z',
      scheduledFor: null,
      media: [{ type: 'video', url: '/assets/posts/motion13.mp4' }],
      tags: ['video', 'performance'],
      authorId: 'user-001',
      metrics: {
        impressions: 218900,
        reach: 171400,
        likes: 10320,
        comments: 982,
        shares: 645,
        saves: 1105,
        clicks: 2380,
        engagementRate: 7.48,
      },
    },
    {
      id: 'post-van-002',
      workspaceId: 'ws-vanta',
      title: 'Teaser Thread',
      caption: 'Ready for next week. Sneak peek in 3 tweets.',
      platforms: ['x'],
      status: 'scheduled',
      createdAt: '2026-04-23T11:30:00Z',
      publishedAt: null,
      scheduledFor: '2026-04-24T13:00:00Z',
      media: [],
      tags: ['teaser'],
      authorId: 'user-001',
      metrics: {
        impressions: 0,
        reach: 0,
        likes: 0,
        comments: 0,
        shares: 0,
        saves: 0,
        clicks: 0,
        engagementRate: 0,
      },
    },
  ],
  'ws-rivet': [
    {
      id: 'post-riv-001',
      workspaceId: 'ws-rivet',
      title: 'Weekend Offers Story',
      caption: 'Swipe up for this weekend’s top deals.',
      platforms: ['instagram', 'facebook'],
      status: 'published',
      createdAt: '2026-04-19T10:14:00Z',
      publishedAt: '2026-04-19T12:00:00Z',
      scheduledFor: null,
      media: [{ type: 'image', url: '/assets/posts/weekend-offer.png' }],
      tags: ['retail', 'promo'],
      authorId: 'user-001',
      metrics: {
        impressions: 93600,
        reach: 73300,
        likes: 3922,
        comments: 301,
        shares: 202,
        saves: 314,
        clicks: 1668,
        engagementRate: 5.06,
      },
    },
    {
      id: 'post-riv-002',
      workspaceId: 'ws-rivet',
      title: 'WhatsApp Broadcast Draft',
      caption: 'Loyalty club exclusive drop goes live tomorrow morning.',
      platforms: ['whatsapp'],
      status: 'draft',
      createdAt: '2026-04-23T07:24:00Z',
      publishedAt: null,
      scheduledFor: null,
      media: [],
      tags: ['whatsapp', 'loyalty'],
      authorId: 'user-001',
      metrics: {
        impressions: 0,
        reach: 0,
        likes: 0,
        comments: 0,
        shares: 0,
        saves: 0,
        clicks: 0,
        engagementRate: 0,
      },
    },
  ],
}

export const NOTIFICATIONS_BY_WORKSPACE = {
  'ws-aurora': [
    {
      id: 'notif-aur-001',
      workspaceId: 'ws-aurora',
      type: 'message',
      severity: 'info',
      title: 'New inbox message',
      body: 'Jordan M. replied to your campaign DM.',
      entityType: 'thread',
      entityId: 'thread-aur-001',
      createdAt: '2026-04-23T17:13:00Z',
      read: false,
    },
    {
      id: 'notif-aur-002',
      workspaceId: 'ws-aurora',
      type: 'post',
      severity: 'success',
      title: 'Post published successfully',
      body: 'Spring Launch Reel is live on Instagram and X.',
      entityType: 'post',
      entityId: 'post-aur-001',
      createdAt: '2026-04-21T10:11:00Z',
      read: true,
    },
    {
      id: 'notif-aur-003',
      workspaceId: 'ws-aurora',
      type: 'approval',
      severity: 'warning',
      title: 'Approval pending',
      body: 'BTS Carousel is waiting for legal review.',
      entityType: 'post',
      entityId: 'post-aur-002',
      createdAt: '2026-04-22T12:20:00Z',
      read: false,
    },
    {
      id: 'notif-aur-004',
      workspaceId: 'ws-aurora',
      type: 'system',
      severity: 'info',
      title: 'Analytics sync complete',
      body: 'Latest engagement metrics are now available.',
      entityType: 'analytics',
      entityId: 'analytics-aur',
      createdAt: '2026-04-23T06:45:00Z',
      read: true,
    },
  ],
  'ws-vanta': [
    {
      id: 'notif-van-001',
      workspaceId: 'ws-vanta',
      type: 'post',
      severity: 'success',
      title: 'Motion Clip #13 exceeded baseline',
      body: 'Performance is 18% above campaign average.',
      entityType: 'post',
      entityId: 'post-van-001',
      createdAt: '2026-04-21T09:45:00Z',
      read: false,
    },
    {
      id: 'notif-van-002',
      workspaceId: 'ws-vanta',
      type: 'system',
      severity: 'warning',
      title: 'Token expiring',
      body: 'Instagram account token expires in 5 days.',
      entityType: 'platform',
      entityId: 'platform-van-ig',
      createdAt: '2026-04-23T03:12:00Z',
      read: false,
    },
  ],
  'ws-rivet': [
    {
      id: 'notif-riv-001',
      workspaceId: 'ws-rivet',
      type: 'message',
      severity: 'info',
      title: 'New WhatsApp response',
      body: 'A customer asked about return policy.',
      entityType: 'thread',
      entityId: 'thread-riv-001',
      createdAt: '2026-04-23T12:03:00Z',
      read: false,
    },
    {
      id: 'notif-riv-002',
      workspaceId: 'ws-rivet',
      type: 'post',
      severity: 'danger',
      title: 'Boost campaign paused',
      body: 'Ad account reached daily spend cap.',
      entityType: 'post',
      entityId: 'post-riv-001',
      createdAt: '2026-04-20T22:18:00Z',
      read: true,
    },
  ],
}

export const MESSAGES_BY_WORKSPACE = {
  'ws-aurora': [
    {
      id: 'thread-aur-001',
      workspaceId: 'ws-aurora',
      platform: 'instagram',
      participant: {
        id: 'client-223',
        name: 'Jordan M.',
        handle: '@jordesign',
        avatar: 'https://i.pravatar.cc/120?img=33',
      },
      lastMessageAt: '2026-04-23T17:12:00Z',
      unreadCount: 2,
      pinned: true,
      messages: [
        {
          id: 'msg-aur-001',
          sender: 'client',
          senderName: 'Jordan M.',
          body: 'Can I feature this reel in my weekly roundup?',
          sentAt: '2026-04-23T16:59:00Z',
          status: 'delivered',
        },
        {
          id: 'msg-aur-002',
          sender: 'client',
          senderName: 'Jordan M.',
          body: 'Also need the posting guidelines.',
          sentAt: '2026-04-23T17:12:00Z',
          status: 'delivered',
        },
      ],
    },
    {
      id: 'thread-aur-002',
      workspaceId: 'ws-aurora',
      platform: 'x',
      participant: {
        id: 'client-819',
        name: 'Tech Orbit',
        handle: '@techorbitdaily',
        avatar: 'https://i.pravatar.cc/120?img=22',
      },
      lastMessageAt: '2026-04-22T21:03:00Z',
      unreadCount: 0,
      pinned: false,
      messages: [
        {
          id: 'msg-aur-003',
          sender: 'agent',
          senderName: 'NEXUS Team',
          body: 'Thanks for the mention! Media kit attached.',
          sentAt: '2026-04-22T21:03:00Z',
          status: 'sent',
        },
      ],
    },
  ],
  'ws-vanta': [
    {
      id: 'thread-van-001',
      workspaceId: 'ws-vanta',
      platform: 'tiktok',
      participant: {
        id: 'client-341',
        name: 'Mila Creative',
        handle: '@milacreates',
        avatar: 'https://i.pravatar.cc/120?img=15',
      },
      lastMessageAt: '2026-04-23T08:44:00Z',
      unreadCount: 1,
      pinned: false,
      messages: [
        {
          id: 'msg-van-001',
          sender: 'client',
          senderName: 'Mila Creative',
          body: 'Can we collaborate on the next trend format?',
          sentAt: '2026-04-23T08:44:00Z',
          status: 'delivered',
        },
      ],
    },
  ],
  'ws-rivet': [
    {
      id: 'thread-riv-001',
      workspaceId: 'ws-rivet',
      platform: 'whatsapp',
      participant: {
        id: 'client-506',
        name: 'Ifeoma B.',
        handle: '+234 812 227 1098',
        avatar: '',
      },
      lastMessageAt: '2026-04-23T12:02:00Z',
      unreadCount: 1,
      pinned: false,
      messages: [
        {
          id: 'msg-riv-001',
          sender: 'client',
          senderName: 'Ifeoma B.',
          body: 'Is same-day delivery available in Abuja?',
          sentAt: '2026-04-23T12:02:00Z',
          status: 'delivered',
        },
      ],
    },
  ],
}

export const ANALYTICS_BY_WORKSPACE = {
  'ws-aurora': {
    range: '30d',
    summary: {
      followers: { current: 128400, previous: 117200, change: 9.56 },
      impressions: { current: 612000, previous: 553200, change: 10.63 },
      engagementRate: { current: 7.82, previous: 6.94, change: 12.68 },
      ctr: { current: 3.12, previous: 2.78, change: 12.23 },
      responseTimeMinutes: { current: 18, previous: 24, change: -25 },
    },
    engagementTrend: [
      { label: 'Mon', value: 6.8 },
      { label: 'Tue', value: 7.1 },
      { label: 'Wed', value: 7.9 },
      { label: 'Thu', value: 8.4 },
      { label: 'Fri', value: 8.1 },
      { label: 'Sat', value: 7.4 },
      { label: 'Sun', value: 7.0 },
    ],
    reachTrend: [
      { label: 'Mon', value: 62400 },
      { label: 'Tue', value: 71500 },
      { label: 'Wed', value: 81200 },
      { label: 'Thu', value: 87600 },
      { label: 'Fri', value: 85200 },
      { label: 'Sat', value: 79400 },
      { label: 'Sun', value: 75600 },
    ],
    platformBreakdown: [
      { platform: 'instagram', followers: 68400, engagementRate: 8.9, trafficShare: 43 },
      { platform: 'x', followers: 31400, engagementRate: 6.4, trafficShare: 27 },
      { platform: 'linkedin', followers: 22600, engagementRate: 5.8, trafficShare: 19 },
      { platform: 'youtube', followers: 6000, engagementRate: 4.9, trafficShare: 11 },
    ],
    topPosts: [
      { postId: 'post-aur-001', title: 'Spring Launch Reel', score: 97 },
      { postId: 'post-aur-004', title: 'Analytics Snapshot', score: 88 },
    ],
  },
  'ws-vanta': {
    range: '30d',
    summary: {
      followers: { current: 86400, previous: 79300, change: 8.95 },
      impressions: { current: 704200, previous: 645100, change: 9.16 },
      engagementRate: { current: 7.31, previous: 6.65, change: 9.92 },
      ctr: { current: 2.88, previous: 2.66, change: 8.27 },
      responseTimeMinutes: { current: 26, previous: 32, change: -18.75 },
    },
    engagementTrend: [
      { label: 'Mon', value: 6.3 },
      { label: 'Tue', value: 6.7 },
      { label: 'Wed', value: 7.0 },
      { label: 'Thu', value: 7.8 },
      { label: 'Fri', value: 7.5 },
      { label: 'Sat', value: 7.1 },
      { label: 'Sun', value: 6.9 },
    ],
    reachTrend: [
      { label: 'Mon', value: 88200 },
      { label: 'Tue', value: 92400 },
      { label: 'Wed', value: 95200 },
      { label: 'Thu', value: 100100 },
      { label: 'Fri', value: 98200 },
      { label: 'Sat', value: 94600 },
      { label: 'Sun', value: 93100 },
    ],
    platformBreakdown: [
      { platform: 'tiktok', followers: 42100, engagementRate: 8.1, trafficShare: 49 },
      { platform: 'instagram', followers: 31200, engagementRate: 7.3, trafficShare: 34 },
      { platform: 'x', followers: 13100, engagementRate: 5.2, trafficShare: 17 },
    ],
    topPosts: [{ postId: 'post-van-001', title: 'Motion Clip #13', score: 99 }],
  },
  'ws-rivet': {
    range: '30d',
    summary: {
      followers: { current: 172300, previous: 165500, change: 4.11 },
      impressions: { current: 512300, previous: 489100, change: 4.74 },
      engagementRate: { current: 5.44, previous: 5.08, change: 7.09 },
      ctr: { current: 4.01, previous: 3.66, change: 9.56 },
      responseTimeMinutes: { current: 14, previous: 18, change: -22.22 },
    },
    engagementTrend: [
      { label: 'Mon', value: 4.9 },
      { label: 'Tue', value: 5.2 },
      { label: 'Wed', value: 5.5 },
      { label: 'Thu', value: 5.7 },
      { label: 'Fri', value: 5.8 },
      { label: 'Sat', value: 5.3 },
      { label: 'Sun', value: 5.1 },
    ],
    reachTrend: [
      { label: 'Mon', value: 60600 },
      { label: 'Tue', value: 64500 },
      { label: 'Wed', value: 68900 },
      { label: 'Thu', value: 70100 },
      { label: 'Fri', value: 72000 },
      { label: 'Sat', value: 65800 },
      { label: 'Sun', value: 61200 },
    ],
    platformBreakdown: [
      { platform: 'facebook', followers: 83400, engagementRate: 4.8, trafficShare: 39 },
      { platform: 'instagram', followers: 70100, engagementRate: 5.7, trafficShare: 35 },
      { platform: 'whatsapp', followers: 18800, engagementRate: 6.1, trafficShare: 26 },
    ],
    topPosts: [{ postId: 'post-riv-001', title: 'Weekend Offers Story', score: 91 }],
  },
}

export const PLATFORM_CONNECTIONS_BY_WORKSPACE = {
  'ws-aurora': [
    { id: 'platform-aur-ig', platform: 'instagram', status: 'connected', account: '@auroralabs' },
    { id: 'platform-aur-x', platform: 'x', status: 'connected', account: '@auroralabs' },
    { id: 'platform-aur-li', platform: 'linkedin', status: 'connected', account: 'Aurora Labs' },
    { id: 'platform-aur-yt', platform: 'youtube', status: 'connected', account: 'Aurora Labs Media' },
  ],
  'ws-vanta': [
    { id: 'platform-van-ig', platform: 'instagram', status: 'expiring', account: '@vantamotion' },
    { id: 'platform-van-tt', platform: 'tiktok', status: 'connected', account: '@vantamotion' },
    { id: 'platform-van-x', platform: 'x', status: 'connected', account: '@vantamotion' },
  ],
  'ws-rivet': [
    { id: 'platform-riv-fb', platform: 'facebook', status: 'connected', account: 'Rivet Retail' },
    { id: 'platform-riv-ig', platform: 'instagram', status: 'connected', account: '@rivetretail' },
    { id: 'platform-riv-wa', platform: 'whatsapp', status: 'connected', account: '+1 415 228 0184' },
  ],
}

export const SCHEDULER_BY_WORKSPACE = {
  'ws-aurora': [
    {
      id: 'event-aur-001',
      workspaceId: 'ws-aurora',
      title: 'Publish BTS Carousel',
      startsAt: '2026-04-26T11:30:00Z',
      status: 'scheduled',
      platform: 'instagram',
      postId: 'post-aur-002',
    },
    {
      id: 'event-aur-002',
      workspaceId: 'ws-aurora',
      title: 'Weekly reporting sync',
      startsAt: '2026-04-27T09:00:00Z',
      status: 'confirmed',
      platform: 'internal',
      postId: null,
    },
  ],
  'ws-vanta': [
    {
      id: 'event-van-001',
      workspaceId: 'ws-vanta',
      title: 'Publish Teaser Thread',
      startsAt: '2026-04-24T13:00:00Z',
      status: 'scheduled',
      platform: 'x',
      postId: 'post-van-002',
    },
  ],
  'ws-rivet': [
    {
      id: 'event-riv-001',
      workspaceId: 'ws-rivet',
      title: 'Loyalty Broadcast',
      startsAt: '2026-04-24T07:45:00Z',
      status: 'draft',
      platform: 'whatsapp',
      postId: 'post-riv-002',
    },
  ],
}

export const WORKSPACE_DATA = {
  'ws-aurora': {
    posts: POSTS_BY_WORKSPACE['ws-aurora'],
    notifications: NOTIFICATIONS_BY_WORKSPACE['ws-aurora'],
    messages: MESSAGES_BY_WORKSPACE['ws-aurora'],
    analytics: ANALYTICS_BY_WORKSPACE['ws-aurora'],
    platforms: PLATFORM_CONNECTIONS_BY_WORKSPACE['ws-aurora'],
    scheduler: SCHEDULER_BY_WORKSPACE['ws-aurora'],
  },
  'ws-vanta': {
    posts: POSTS_BY_WORKSPACE['ws-vanta'],
    notifications: NOTIFICATIONS_BY_WORKSPACE['ws-vanta'],
    messages: MESSAGES_BY_WORKSPACE['ws-vanta'],
    analytics: ANALYTICS_BY_WORKSPACE['ws-vanta'],
    platforms: PLATFORM_CONNECTIONS_BY_WORKSPACE['ws-vanta'],
    scheduler: SCHEDULER_BY_WORKSPACE['ws-vanta'],
  },
  'ws-rivet': {
    posts: POSTS_BY_WORKSPACE['ws-rivet'],
    notifications: NOTIFICATIONS_BY_WORKSPACE['ws-rivet'],
    messages: MESSAGES_BY_WORKSPACE['ws-rivet'],
    analytics: ANALYTICS_BY_WORKSPACE['ws-rivet'],
    platforms: PLATFORM_CONNECTIONS_BY_WORKSPACE['ws-rivet'],
    scheduler: SCHEDULER_BY_WORKSPACE['ws-rivet'],
  },
}

export const DEFAULT_WORKSPACE_ID = WORKSPACES[0].id

export const findWorkspaceById = (workspaceId) => {
  if (!workspaceId) {
    return null
  }

  return WORKSPACES.find((workspace) => workspace.id === workspaceId) ?? null
}

export const getWorkspaceData = (workspaceId = DEFAULT_WORKSPACE_ID) => {
  const safeWorkspaceId = WORKSPACE_DATA[workspaceId] ? workspaceId : DEFAULT_WORKSPACE_ID
  return cloneDeep(WORKSPACE_DATA[safeWorkspaceId])
}

export const MOCK_DATA = {
  user: DEMO_USER,
  credentials: DEMO_CREDENTIALS,
  twoFA: TWO_FA_CONFIG,
  workspaces: WORKSPACES,
  workspaceData: WORKSPACE_DATA,
  analytics: ANALYTICS_BY_WORKSPACE,
  scheduler: SCHEDULER_BY_WORKSPACE,
  platforms: PLATFORM_CONNECTIONS_BY_WORKSPACE,
}

export default MOCK_DATA
